name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # פקודה זו מבטלת את בדיקת האבטחה לקובץ ה-jar הפגום
          validate-wrappers: false

      - name: Build with Gradle
        # שימוש בפקודה 'gradle' במקום './gradlew'
        run: gradle assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        # שלב זה מופעל רק אם הבנייה הצליחה, כדי שתוכל להוריד את הקובץ
        if: success()
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/**/*.apk
