name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        # כאן אנחנו משתמשים ב-gradlew שנמצא בתיקייה הראשית של הפרויקט שלך
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
